"""Initial

Revision ID: 50621a6730b6
Revises: 
Create Date: 2023-06-04 03:31:05.782060

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '50621a6730b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('user', 'username',
                    existing_type=sa.VARCHAR(length=25),
                    nullable=False)
    op.alter_column('user', 'email',
                    existing_type=sa.VARCHAR(length=80),
                    nullable=False)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_column('user', 'is_staff')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.alter_column('user', 'email',
                    existing_type=sa.VARCHAR(length=80),
                    nullable=True)
    op.alter_column('user', 'username',
                    existing_type=sa.VARCHAR(length=25),
                    nullable=True)
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
