"""first

Revision ID: cd0405636bd1
Revises: 
Create Date: 2023-06-09 21:10:50.796385

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd0405636bd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    DAY_OF_WEEK = (
        ("ПОНЕДЕЛЬНИК", "Понедельник"),
        ("ВТОРНИК", "Вторник"),
        ("СРЕДА", "Среда"),
        ("ЧЕТВЕРГ", "Четверг"),
        ("ПЯТНИЦА", "Пятница"),
        ("СУББОТА", "Суббота"),
    )

    PARITY = (
        ("чёт", "Чётная"),
        ("нечёт", "Нечётная")
    )
    op.create_table('booked_audience',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('audience', sa.String(length=10), nullable=True),
                    sa.Column('event', sa.String(), nullable=False),
                    sa.Column('day_of_week', sqlalchemy_utils.types.choice.ChoiceType(DAY_OF_WEEK), nullable=True),
                    sa.Column('parity', sqlalchemy_utils.types.choice.ChoiceType(PARITY), nullable=True),
                    sa.Column('start_of_class', sa.Time(), nullable=True),
                    sa.Column('end_of_class', sa.Time(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('audience', sa.Column('equipment', sa.String(), nullable=True))
    op.add_column('audience', sa.Column('addition', sa.String(), nullable=True))
    op.drop_constraint('audience_user_id_fkey', 'audience', type_='foreignkey')
    op.drop_column('audience', 'user_id')
    op.drop_column('audience', 'event')
    op.drop_column('audience', 'end_of_class')
    op.drop_column('audience', 'start_of_class')
    op.drop_column('audience', 'parity')
    op.drop_column('audience', 'day_of_week')
    op.drop_column('audience', 'audience')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audience', sa.Column('audience', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('audience', sa.Column('day_of_week', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('audience', sa.Column('parity', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('audience', sa.Column('start_of_class', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('audience', sa.Column('end_of_class', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('audience', sa.Column('event', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('audience', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('audience_user_id_fkey', 'audience', 'user', ['user_id'], ['id'])
    op.drop_column('audience', 'addition')
    op.drop_column('audience', 'equipment')
    op.drop_table('booked_audience')
    # ### end Alembic commands ###
